### ISSUE TITLE
摇杆的背景与摇杆摇动的背景无法改变吗？

### ISSUE THREAD

**Issue by zz5221** [kongqw/KqwRockerDemo#3]
在使用过程中，添加到Layout 文件中的过程中，kongqw： 关键字无法识别啊。

**Comment by kongqw** [comment]
使用自定义属性，要添加命名空间
``` XML
xmlns:kongqw="http://schemas.android.com/apk/res-auto"
```

详见 [activity_main.xml](https://github.com/kongqw/AndroidRocker/blob/master/app/src/main/res/layout/activity_main.xml)
